#! /usr/bin/env bash

function enc() {
  local input
  if [ "$#" -eq 1 ]; then
    input=$1
  else
    input=$(cat)
  fi
  openssl enc -aes-256-cbc -a -salt -pbkdf2 -iter 10000 -pass pass:"$DECRYPT_PASSPHRASE" <<< "$input"
}

function dec() {
  local input
  if [ "$#" -eq 1 ]; then
    input=$1
  else
    input=$(cat)
  fi
  openssl enc -aes-256-cbc -d -a -salt -pbkdf2 -iter 10000 -pass pass:"$DECRYPT_PASSPHRASE" <<< "$input"
}

echo -e "${blue}Status: ${green}$(dec "U2FsdGVkX1/3w1U3scW6rxwsABkYpmZ1aAW4IrBD+ho=")${end}"
