#! /usr/bin/env bash


#######################################################################
# Author:           Benjamin Hudgens
# Date:             April 9, 2015
#
# Description:      Aliases and Shortcuts
#######################################################################

#############################################################################
# Rapid Reverts
#############################################################################
# Revert the last normal commit
alias gr='git revert HEAD~1..HEAD'
# Revert the last commit if it's a merge
alias gmr='git revert -m 1 HEAD~1..HEAD'

#############################################################################
# Navigation
#############################################################################
alias priv='cat ${HOME}/.ssh/id_rsa | pbcopy'
alias pub='cat ${HOME}/.ssh/id_rsa.pub | pbcopy'
alias ssh='ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null'
# ls shortcuts
alias ls='ls -G'
alias ll='ls -lh'
alias lsa='ls -lah'
alias la='ls -lAh'
alias l='ls -lah'
alias rv='mkdir -p "${DIR_REVERTS}"; cd "${DIR_REVERTS}"'
alias cs='cd "/mnt/g/My Drive/CodeShare"'

#############################################################################
# Shell Shortcuts
#############################################################################
alias flushdns='sudo killall -HUP mDNSResponder'
alias md='mkdir -p'
alias history='fc -l 1'
alias ol='app https://outlook.office.com/owa/'
alias ttl="sudo sysctl -w net.inet.ip.ttl=65"
alias bus="sudo sysctl -w net.inet.ip.ttl=66"
alias remap="xmodmap ${HOME}/.keymaps"
alias dm="${HOME}/reverts/devmode/bin/devmode \
            --ldapUsername bhudgens \
            --starphleetSourceDir '${HOME}/reverts/starphleet'"

#############################################################################
# Terraform  Shortcuts
#############################################################################
alias tfr='terraform fmt -recursive'

#############################################################################
# Git Shortcuts
#############################################################################
alias g='git'
alias ggpull='git pull origin $(current_branch)'
alias gwc='git whatchanged -p --abbrev-commit --pretty=medium'
alias gunwip='git log -n 1 | grep -q -c 'wip' && git reset HEAD~1'
alias glgga='git log --graph --decorate --all'
alias ggpush='git push origin $(current_branch)'
alias gsd='git svn dcommit'
alias grbc='git rebase --continue'
alias gts='git tag -s'
alias gdt='git difftool'
alias gstp='git stash pop'
alias gsps='git show --pretty=short --show-signature'
alias gc='git commit -v'
alias gcp='git cherry-pick'
alias gcl='git config --list'
alias grh='git reset HEAD'
alias gsta='git stash'
alias gg='git gui citool'
alias grbi='git rebase -i'
alias gcs='git commit -S'
alias gup='git pull --rebase'
alias grba='git rebase --abort'
alias gc!='git commit -v --amend'
alias gm='git merge'
alias glp='_git_log_prettily'
alias glgg='git log --graph --max-count=10'
alias gbr='git branch --remote'
alias gdc='git diff --cached'
alias gsts='git stash show --text'
alias ggpur='git pull --rebase origin $(current_branch)'
alias gunignore='git update-index --no-assume-unchanged'
# alias ggpnp='git pull origin $(current_branch) && git push origin $(current_branch)'
alias grv='git remote -v'
alias gst='git status'
alias gcm='git checkout master'
alias gcount='git shortlog -sn'
alias glo='git log --oneline --decorate --color'
alias git-svn-dcommit-push='git svn dcommit && git push github master:svntrunk'
alias gba='git branch -a'
alias gca!='git commit -v -a --amend'
alias gap='git add --patch'
alias gga='git gui citool --amend'
alias gwip='git add -A; git ls-files --deleted -z | xargs -r0 git rm; git commit -m '--wip--''
alias gsr='git svn rebase'
alias grup='git remote update'
alias gk='gitk --all --branches'
alias gco='git checkout'
alias gstd='git stash drop'
alias gpoat='git push origin --all && git push origin --tags'
alias gd='git diff'
alias gmt='git mergetool --no-prompt'
alias grrm='git remote remove'
alias gca='git commit -v -a'
alias gignore='git update-index --assume-unchanged'
alias grset='git remote set-url'
alias gp='git push'
alias gb='git branch'
alias grhh='git reset HEAD --hard'
alias gclean='git reset --hard && git clean -dfx'
alias glog='git log --oneline --decorate --color --graph'
alias ga='git add'
alias gvt='git verify-tag'
alias gcmsg='git commit -m'
alias gl='git pull'
alias gss='git status -s'
alias me='sudo pactl load-module module-loopback latency_msec=1'
alias nme='sudo pactl unload-module module-loopback'
alias myip='curl "https://api.ipify.org?format=json"'
alias denv='source <(bwGetNote "Development Environment")'
alias aws='docker run --rm -it -v ~/.aws:/root/.aws -v $(pwd):/aws --env AWS_SESSION_TOKEN --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_PAGER="" bhudgens/aws-cli'

alias record='asciinema rec'

alias xcodeaccept="sudo xcodebuild -license accept"
alias dev="cd $HOME/reverts/ec2.starphleet.dev.headquarters"

if [ ! -d "/mnt/c" ]; then
  alias pbcopy='xsel --clipboard --input'
  alias pbpaste='xsel --clipboard --output'
fi

if [ -d "/mnt/c" ]; then
  alias pbcopy='clip.exe'
  alias pbpaste='powershell.exe -command "Get-Clipboard"'
fi

alias prompt="export PROMPT='%{%f%b%k%}\$(build_prompt) '"

alias cisco="ssh -oKexAlgorithms=+diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1 -oHostKeyAlgorithms=+ssh-rsa "

# All finished
