#! /usr/bin/env bash

glglogin() {
  if ! bw status | jq -r '.userEmail' | grep -q 'glgroup.com'; then
    API_KEY="$(bw get item d9156b54-fcf2-4d2a-bee8-b0f200e61b86)"
    export BW_CLIENTID="$(echo "$API_KEY" | jq -r '.login.username')"
    export BW_CLIENTSECRET="$(echo "$API_KEY" | jq -r '.login.password')"

    MP="$(bw get item 1778eacd-bc34-4441-853f-b0de0150c2af)"
    export BW_MP="$(echo "$MP" | jq -r '.login.password')"

    bw logout
    bw login --apikey
    export BW_SESSION="$(bw unlock --passwordenv BW_MP --raw)"
  else
    echo "Already logged in to other profile"
  fi
}
