#!/usr/bin/env bash
#############################################################################
# Utility Function(s)
#############################################################################
function _which () {
  which $1 > /dev/null
}

#############################################################################
# Checkout our dotfiles
#############################################################################
DOT_FILES_REPO=${DOT_FILES_REPO:-"https://github.com/bhudgens/dotfiles.git"}
if [ ! -d "$HOME/.dotfiles" ]; then
  2>&1 git clone "${DOT_FILES_REPO}" "$HOME/.dotfiles" > /dev/null
fi

for dotfile in .zshrc .tmux.conf; do
  install_dot_file "$dotfile"
done
