#!/usr/bin/env bash
#############################################################################
# Utility Function(s)
#############################################################################
function _which () {
  which $1 > /dev/null
}

# Skip configs setup if SSH key doesn't exist yet
if [ ! -f "${HOME}/.ssh/id_rsa" ]; then
  return 0
fi

#############################################################################
# Checkout our dotfiles
#############################################################################
DOT_FILES_REPO=${DOT_FILES_REPO:-"https://github.com/bhudgens/dotfiles.git"}
if [ ! -d "$HOME/.dotfiles" ]; then
  2>&1 git clone "${DOT_FILES_REPO}" "$HOME/.dotfiles" > /dev/null
fi

pushd "$HOME/.dotfiles" > /dev/null
  2>&1 git pull > /dev/null
popd > /dev/null

for dotfile in .zshrc .tmux.conf; do
  install_dot_file "$dotfile"
done

#############################################################################
# Oh-My-Zsh Custom Plugins
#############################################################################
ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
if [ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ]; then
  2>&1 git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions" > /dev/null
fi
