#! /usr/bin/env bash

if echo $OSTYPE | grep -i linux > /dev/null; then

  # Which version of node do we wanna install
  NODE_MAJOR=20


  if ! _which nodejs; then
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" \
      | sudo tee /etc/apt/sources.list.d/nodesource.list
    apt_get_install ca-certificates
    apt_get_install curl
    apt_get_install gnupg
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    apt_get_install nodejs
  fi

  apt_get_install apt-utils apt-extracttemplates
  apt_get_install locales update-locale
  apt_get_install npm
  apt_get_install bsdmainutils column
  apt_get_install unzip
  apt_get_install git
  apt_get_install curl
  apt_get_install xsel
  apt_get_install sudo
  apt_get_install wget
  apt_get_install tmux
  apt_get_install openvpn
  apt_get_install traceroute
  apt_get_install nmap
  apt_get_install strace
  apt_get_install jq
  apt_get_install silversearcher-ag ag
  # Needed for coc-lua lsp server vim plugin
  # Link: https://stackoverflow.com/questions/20079572/srlua-makefile-error-lua-h-no-such-file-or-directory/20080097
  apt_get_install "lua5.3" lua
  apt_get_install "liblua5.3-dev" lua

  if [ ! -f "/usr/bin/lua" ] \
  && [ -f "/usr/bin/lua5.3" ]; then
    ln -s "/usr/bin/lua5.3" "/usr/bin/lua"
  fi
  # These two collide right now so this is temporary.  See issue below
  # apt_get_install bat batcat
  # apt_get_install ripgrep rg
  # Fixing Bug: https://github.com/sharkdp/bat/issues/938#issuecomment-646745610
  if (! _which batcat && ! _which bat) \
  || ! _which rg; then
    eval "$SUDO apt-get install -o Dpkg::Options::='--force-overwrite' -y bat ripgrep"
  fi

  if type rg &> /dev/null; then
    export FZF_DEFAULT_COMMAND='rg --files'
    export FZF_DEFAULT_OPTS='-m --height 50% --border'
  fi

  # Ensure tools directory exists
  mkdir -p "$HOME/run/tools"

  # List of tools to download if missing
  for tool in $BENVIRONMENT_TOOLS_LIST; do
    if [ ! -f "$HOME/run/tools/${tool}" ]; then
      curl -s "${URL_PATH_TO_ENV_FILES}/tools/${tool}" -o "$HOME/run/tools/${tool}"
      chmod +x "$HOME/run/tools/${tool}"
    fi
  done

  # Source custom tool installation scripts
  for tool_script in $HOME/run/tools/*; do
    if [ -f "$tool_script" ]; then
      source "$tool_script"
    fi
  done
fi

# When installing modules with npm always pin version
npm config set save-prefix ''

#############################################################################
# Global Configs
#############################################################################
# If bat successfully gets installed we will
# swap cat with bat
if _which batcat; then
  alias cat='batcat'
fi

if [ -f /usr/local/bin/prettyping ]; then
  alias ping='prettyping --nolegend'
fi

if _which locale-gen \
&& ! grep 'en_US.UTF-8' /etc/default/locale > /dev/null;
then
  eval "$SUDO locale-gen 'en_US.UTF-8'"
  eval "$SUDO update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8"
fi

if [ ! -f "$HOME/.gitconfig" ]; then
  userEmail=$(dec "U2FsdGVkX18H/ngbZbImHfPsDwpE7/9/11qJ/Nt4bpOM5HlnwNlS45obrq+/f6WC")
  if [ $? -eq 0 ]; then
    git config --global user.email "$userEmail"
    git config --global user.name "Benjamin Hudgens"
  fi
fi

