#! /usr/bin/env bash

GDS_REPO_DIR="$HOME/run/gds"

function _pushd() {
  pushd "$1" > /dev/null
}

function _popd() {
  popd > /dev/null
}

function _getClusterConfigsAndServices() {
  _pushd "$GDS_REPO_DIR"
  egrep '\[Link\]' ./clusterconfigs/* \
    | perl -pe 's/.*\/(.*?):\|\s+\[(.*?)\]\((.*?)\).*?\((.*?)\).*?\((.*?)\).*?\((.*?)\).*?\((.*?)\).*?\((.*?)\).*/$1 $2 $3 $4 $5 $6 $7 $8/'
}

function _tinyUrl() {
  local url="$1"
  local scrubbedUrl=$(python3 -c "import urllib.parse; print(urllib.parse.quote_plus('$url'))");
  local tiny=$(curl -sLo- "http://tny.im/yourls-api.php?action=shorturl&format=simple&url=$scrubbedUrl")

  # The tiny url thing has conservative limits; if we blow 'em stop using it
  if echo "$tiny" | grep "Slow down please" > /dev/null; then
    false
  else
    echo "$tiny"
  fi

}

