#! /usr/bin/env bash

GDS_REPO_DIR="$HOME/run/gds"

function _pushd() {
  pushd "$1" > /dev/null
}

function _popd() {
  popd > /dev/null
}

function _getGDSRepo() {
}

function _getClusterConfigsAndServices() {
  _pushd "$GDS_REPO_DIR"
  egrep '\[Link\]' ./clusterconfigs/* \
    | perl -pe 's/.*\/(.*?):\|\s+\[(.*?)\]\((.*?)\).*?\((.*?)\).*?\((.*?)\).*?\((.*?)\).*?\((.*?)\).*?\((.*?)\).*/$1 $2 $3 $4 $5 $6 $7 $8/'
}

function _tinyUrl() {
  local url=$(python3 -c "import urllib.parse; print(urllib.parse.quote_plus('$1'))");
  curl -sLo- "http://tny.im/yourls-api.php?action=shorturl&format=simple&url=$url"
}

function links() {
  [ ! -d "$GDS_REPO_DIR" ] && git clone git@github.com:glg/gds.git "$GDS_REPO_DIR"
  local search="$1"
  local everything=$(_getClusterConfigsAndServices)
  local onlyClusterAndService=$(echo "$everything" | cut -f1,2 -d " ")
  local table="Cluster Service"$'\n'"$onlyClusterAndService"
  table=$(echo "$table" | column -s' ' -t)
  IFS=$'\n'
  for clusterAndService in $(echo "$table" | fzf --layout=reverse --header-lines=1 ${search:+"-q $search"}); do
    local cluster=$(echo $clusterAndService | awk '{print $1}')
    local service=$(echo $clusterAndService | awk '{print $2}')
    local clusterFile="$GDS_REPO_DIR/clusterconfigs/$cluster"
    local ccWatcherLink=$(cat "$clusterFile" | grep "Cluster Config Watcher" | perl -pe 's|.*\((.*)\).*|$1|')
    local ECSCluster=$(cat "$clusterFile" | grep "ECS Cluster" | perl -pe 's|.*\((.*)\).*|$1|')
    local sumoClusterDashboard=$(cat "$clusterFile" | grep "Sumo Cluster Dashboard" | perl -pe 's|.*\((.*)\).*|$1|')
    local gitRepo=$(echo "$everything" | egrep "^$cluster\s+$service\s+" | awk '{print $3}')
    local healthcheck=$(echo "$everything" | egrep "^$cluster\s+$service\s+" | awk '{print $4}')
    local deployLogs=$(echo "$everything" | egrep "^$cluster\s+$service\s+" | awk '{print $5}')
    local sumoServiceDashboard=$(echo "$everything" | egrep "^$cluster\s+$service\s+" | awk '{print $6}')
    local ECSService=$(echo "$everything" | egrep "^$cluster\s+$service\s+" | awk '{print $7}')
    local githubOrders=$(echo "$everything" | egrep "^$cluster\s+$service\s+" | awk '{print $8}')
    echo -e "${white}${cluster} | ${service}${end}"
    echo -e "
      ${blue}CC Watcher | ${yellow}$ccWatcherLink${end}
      ${blue}ECS Cluster | ${yellow}$ECSCluster${end}
      ${blue}Sumo Cluster | ${yellow}$(_tinyUrl "$sumoClusterDashboard")${end}
      ${blue}Github | ${yellow}$gitRepo${end}
      ${blue}Healthcheck | ${yellow}$healthcheck${end}
      ${blue}Deploy Logs | ${yellow}$deployLogs${end}
      ${blue}Sumo Service | ${yellow}$(_tinyUrl $sumoServiceDashboard)${end}
      ${blue}ECS Service | ${yellow}$ECSService${end}
      ${blue}Orders File | ${yellow}$githubOrders${end}
    " | column -s"|" -t
  done
  # Do slow things last
  # --
  # We'll update our links passively at the end which will be fine
  # -most- of the time
  _pushd "$GDS_REPO_DIR"; 2>&1 git pull > /dev/null; _popd
}

