#!/usr/bin/env bash

############################################################################
## How to use:
##
## - Create a new private note in lastpass
## - Make the note a json with the following form:
##   {
##     "Provider":"MFA Secret"
##   }
## - Save private note
## - Set the following environment variable to the ID of the lastpass note:
##   export LASTPASS_MFA_SECRETS_ID="Your Secret Note ID"
## - Source this file
## - Run `mfa`
##
## This tool will use the keys from the note and let you select which code
## you want to grab.  This will automatically copy the code to your clipboard
############################################################################

function _which() {
  which $1 > /dev/null
}

function _punt() {
  echo "$1"
  exit 1
}

function _outputMFACode() {
local code="$1"
cat << EOF
Code copied to your clipboard

  Code   : ${code}
EOF
}

function mfa() {
  _bwUnlock

  local header='Name|Id'
  local list="$(bw list items | jq -r '.[] | select(.login.totp != null) | .name + "|" + .id')"
  local table="$(echo ${header}$'\n'${list} | column -s'|' -t)"

  local selectedAccount=$(echo "$table" | fzf --layout=reverse --header-lines=1)
  local id=$(echo $selectedAccount | perl -pe 's|.*(\w{8}-\w{4}-\w{4}-\w{4}-\w{12})|$1|')
  local code=$(bw get totp "$id")
  _which pbcopy && echo -n "${code}" | pbcopy
  _which xsel && echo -n "${code}" | xsel --clipboard --input
  _outputMFACode "$code"
}
