#! /usr/bin/env bash

#############################################################################
# Utility Function(s)
#############################################################################
# shhhhh
function _which () {
  which "$1" > /dev/null 2>&1
}

[ "$EUID" -ne 0 ] && _which sudo && SUDO="sudo -E "

#############################################################################
# Software Install - Mac Poo
#############################################################################
brew_install () {
  BREW_FORMULA="$1"
  BREW_CHECK="${2:-$1}"
  if ! _which brew; then
    echo Brew not found
    return
  fi

  if ! _which "${BREW_CHECK}"; then
    brew install "${BREW_FORMULA}"
  fi
}

brew_cask_install () {
  BREW_CASK="$1"
  if ! _which brew; then
    echo Brew not found
    return
  fi

  brew list --cask "${BREW_CASK}" > /dev/null 2>&1 || brew install --cask "${BREW_CASK}"
}

#############################################################################
# Software Install - Linux Poo
#############################################################################
apt_get_install () {
  APP="$(basename $1)"
  [ -n "$2" ] && CHECK="$2" || CHECK="$1"
  if ! _which "$CHECK"; then
    [ -z "${RUN_ONCE}" ] && eval "$SUDO apt-get update -y" && RUN_ONCE=true
    eval "DEBIAN_FRONTEND=noninteractive $SUDO apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' install -y $APP"
  fi
}

npm_install () {
  APP="$(basename $1)"
  [ -z "$2" ] || APP="$2"
  if ! _which "${APP}" \
  && _which npm; then
    if echo "$OSTYPE" | grep -i darwin > /dev/null; then
      mkdir -p "${HOME}/.npm-global"
      npm config set prefix "${HOME}/.npm-global"
      export PATH="${HOME}/.npm-global/bin:${PATH}"
      npm install -g "$1"
    else
      eval "$SUDO mkdir -p /usr/lib/node_modules"
      eval "$SUDO mkdir -p /usr/local/lib/node_modules"
      eval "$SUDO chown -R ${USER}:${USER} /usr/lib/node_modules"
      eval "$SUDO chown -R ${USER}:${USER} /usr/local/lib/node_modules"
      eval "$SUDO chown root:adm /usr/bin"
      eval "$SUDO chmod 775 /usr/bin"
      eval "$SUDO chown root:adm /usr/local/bin"
      eval "$SUDO chmod 775 /usr/local/bin"
      eval "$SUDO npm install -g $1"
      [ -d "${HOME}/.npm" ] && eval "$SUDO chown -R ${USER}:${USER} ${HOME}/.npm"
    fi
  fi
}

#############################################################################
# Install dotfiles (files and directories) from ~/.dotfiles into $HOME
#############################################################################
function install_dot_file () {
  local dotfile="$1"
  if [ ! -L "${HOME}/${dotfile}" ] \
  && [ -f "${HOME}/.dotfiles/${dotfile}" ]; then
    mkdir -p "$(dirname "${HOME}/${dotfile}")"
    [ -f "${HOME}/${dotfile}" ] && mv "${HOME}/${dotfile}" "${HOME}/${dotfile}.bak"
    ln -s "${HOME}/.dotfiles/${dotfile}" "${HOME}/${dotfile}"
  fi
}

function install_dot_dir () {
  local dotdir="$1"
  if [ ! -L "${HOME}/${dotdir}" ] \
  && [ -d "${HOME}/.dotfiles/${dotdir}" ]; then
    mkdir -p "$(dirname "${HOME}/${dotdir}")"
    [ -d "${HOME}/${dotdir}" ] && mv "${HOME}/${dotdir}" "${HOME}/${dotdir}.bak"
    ln -s "${HOME}/.dotfiles/${dotdir}" "${HOME}/${dotdir}"
  fi
}
