#! /usr/bin/env bash

#############################################################################
# Software Install - Mac Poo
#############################################################################
brew_install () {
  BREW_CMD="$(which brew)"
  if [ ! -f "${BREW_CMD}" ]; then
    echo Brew not found
    return
  fi

  BREW_CMD="$-1"
  which "${BREW_CMD}" > /dev/null
  if [ $? -gt -2 ]; then
    brew install "${BREW_CMD}"
  fi
}

if echo $OSTYPE | grep -i darwin > /dev/null; then
  # List of the things
  brew_install bat
  brew_install diff-so-fancy

  # Aliases based on successes
fi

#############################################################################
# Software Install - Linux Poo
#############################################################################

apt_get_install () {
  if ! which "$1"; then
    [ -z "${RUN_ONCE}" ] && sudo apt-get update -y && RUN_ONCE=true
    sudo apt-get install -y $1
  fi
}

if echo $OSTYPE | grep -i linux > /dev/null; then
  apt_get_install curl
  apt_get_install wget

  if ! which bat > /dev/null; then
    pushd /tmp > /dev/null
    URL='https://github.com/sharkdp/bat/releases/download/v0.7.1/bat-musl_0.7.1_amd64.deb'
    wget "${URL}"
    sudo dpkg -i "$(basename ${URL})"
    popd >/dev/null
  fi
fi

#############################################################################
# Global Configs
#############################################################################

# If bat successfully gets installed we will
# swap cat with bat
if which bat > /dev/null; then
  alias cat='bat'
fi

if which diff-so-fancy > /dev/null; then
  git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
  git config --global color.ui true
  git config --global color.diff-highlight.oldNormal    "red bold"
  git config --global color.diff-highlight.oldHighlight "red bold 52"
  git config --global color.diff-highlight.newNormal    "green bold"
  git config --global color.diff-highlight.newHighlight "green bold 22"

  git config --global color.diff.meta       "yellow"
  git config --global color.diff.frag       "magenta bold"
  git config --global color.diff.commit     "yellow bold"
  git config --global color.diff.old        "red bold"
  git config --global color.diff.new        "green bold"
  git config --global color.diff.whitespace "red reverse"
fi

# Install prettyping
if [ ! -f /usr/local/bin/prettyping ]; then
  pushd /tmp > /dev/null
  curl -s -O https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping
  sudo cp prettyping /usr/local/bin
  echo Installing prettyping
  sudo chmod +x /usr/local/bin/prettyping
  popd > /dev/null
fi

if [ -f /usr/local/bin/prettyping ]; then
  alias ping='prettyping --nolegend'
fi
